<div class="hero-unit">
    <h1><span class="ensemble">Ensemble</span> admin</h1>
    <p>This is the interface for administration of your modules. You can manage pages, modify their contents and update other settings like user permissions and page domains.</p>
</div>

<div class="row-fluid">
    <div class="span4">
        <h2>Pages on the left</h2>
        <p>On the left side a tree view of all your pages is visible. While it is a static list at this moment, it will become a tree where you can drag &amp; drop your pages to the right location, create new ones or delete obsolete pages. It will also give access to page settings (like title, url etcetera) and the module's content. Click on a page title and the appropriate module renders an interface to update the page.</p>
    </div>

    <div class="span4">
        <h2>Links at the top</h2>
        <p>In the bar at the top links can appear. Those links will be pointing to central pieces of ensemble, for example user management. But you can also add more links as shortcuts, for example to have easy access to your blog. In the future you can add pages as much as you like!</p>
    </div>

    <div class="span4">
        <h2>Widgets at the center</h2>
        <p>In the future this center part of this page will be filled with widgets. Ensemble might provide a few default ones, but modules can supply widgets too. And whilst you write your own modules, you determine what kind of additional features you might have on this page.</p>
    </div>
</div>
