<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

$this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript',
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="nl">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Ensemble admin') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?= $this->url('zfcadmin')?>">Admin interface</a>
          <div class="nav-collapse">
            <?= $this->navigation('admin_navigation')->menu()
                                   ->setUlClass('nav')
                                   ->setMaxDepth(0)
                                   ->setRenderInvisible(false)?>?>
            <ul class="nav pull-right">
                <li><a target="_blank" href="/">Open website</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
    <div class="row-fluid">

      <div class="span3">
        <div class="well sidebar-nav">
            <?php echo $this->adminPageTree(); ?>
        </div>
      </div>

      <div class="span9">
        <?php echo $this->content; ?>
      </div>

    </div>

    <hr>
    <footer>
        <p>Ensemble is an open source product. You can find out more about ensemble at <a href="http://ensemble.github.com">ensemble.github.com</a>.</p>
      </footer>
    </div> <!--/.fluid-container-->

    <?php echo $this->inlineScript(); ?>

  </body>
</html>
